<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="indirections" nsURI="http://palladiosimulator.org/Indirections/1.0"
    nsPrefix="org.palladiosimulator.indirections">
  <eClassifiers xsi:type="ecore:EClass" name="JavaClassRealization" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realizingClassFqn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configEntries" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="actions" nsURI="http://palladiosimulator.org/Indirections/Actions/1.0"
      nsPrefix="org.palladiosimulator.indirections.actions">
    <eClassifiers xsi:type="ecore:EClass" name="DataAction" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/AbstractAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableReference" lowerBound="1"
          eType="ecore:EClass platform:/plugin/de.uka.ipd.sdq.stoex/model/stoex.ecore#//VariableReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnalyseStackAction" eSuperTypes="#//actions/DataAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="measurementIdentificationKey"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumeDataAction" eSuperTypes="#//actions/DataAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSinkRole" ordered="false"
          lowerBound="1" eType="#//repository/DataSinkRole"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmitDataAction" eSuperTypes="#//actions/DataAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSourceRole" lowerBound="1"
          eType="#//repository/DataSourceRole"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateDateAction" eSuperTypes="#//actions/DataAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableUsages" upperBound="-1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//parameter/VariableUsage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AddToDateAction" eSuperTypes="#//actions/DataAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableUsages" upperBound="-1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//parameter/VariableUsage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataIteratorAction" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/AbstractLoopAction #//actions/DataAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="PutTimeOnStackAction" eSuperTypes="#//actions/DataAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="RegroupDataAction" abstract="true"
        eSuperTypes="#//actions/DataAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaClassRegroupDataAction" eSuperTypes="#//actions/RegroupDataAction #//JavaClassRealization"/>
  </eSubpackages>
  <eSubpackages name="composition" nsURI="http://palladiosimulator.org/Indirections/Composition/1.0"
      nsPrefix="org.palladiosimulator.indirections.composition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="All connectors for sink/source roles that are either bound to a data channel or to an assembly context, e.g. for a Basic Component"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataChannelToAssemblyContextConnector"
        eSuperTypes="#//composition/abstract/DataChannelSourceConnector #//composition/abstract/AssemblyContextSinkConnector"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContextToDataChannelConnector"
        eSuperTypes="#//composition/abstract/AssemblyContextSourceConnector #//composition/abstract/DataChannelSinkConnector"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataChannelToDataChannelConnector"
        eSuperTypes="#//composition/abstract/DataChannelSourceConnector #//composition/abstract/DataChannelSinkConnector"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContextToAssemblyContextConnector"
        eSuperTypes="#//composition/abstract/AssemblyContextSourceConnector #//composition/abstract/AssemblyContextSinkConnector"/>
    <eSubpackages name="abstract" nsURI="http://palladiosimulator.org/Indirections/Composition/Abstract/1.0"
        nsPrefix="org.palladiosimulator.indirections.composition.abstract">
      <eClassifiers xsi:type="ecore:EClass" name="DataSourceSinkConnector" abstract="true"
          eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/Connector">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Connector between a source and a sink of data."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSourceRole" ordered="false"
            lowerBound="1" eType="#//repository/DataSourceRole"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSinkRole" ordered="false"
            lowerBound="1" eType="#//repository/DataSinkRole"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataChannelSourceConnector" abstract="true"
          eSuperTypes="#//composition/abstract/DataSourceSinkConnector">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Connector that has a DataChannel as its source."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sourceDataChannel"
            ordered="false" lowerBound="1" eType="#//repository/DataChannel"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataChannelSinkConnector" abstract="true"
          eSuperTypes="#//composition/abstract/DataSourceSinkConnector">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Connector that has a DataChannel as its sink."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sinkDataChannel" ordered="false"
            lowerBound="1" eType="#//repository/DataChannel"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssemblyContextSourceConnector"
          abstract="true" eSuperTypes="#//composition/abstract/DataSourceSinkConnector">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Connector that has an AssemblyContext as its source."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAssemblyContext"
            ordered="false" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssemblyContextSinkConnector" abstract="true"
          eSuperTypes="#//composition/abstract/DataSourceSinkConnector">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Connector that has an AssemblyContext as its sink.&lt;p>TODO: should check whether the given sink role fits to the pushing service"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sinkAssemblyContext"
            ordered="false" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pushesTo" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Signature">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="If this is empty, then the connector does not push. If it is set, the connection is pushing."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="pushing" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            volatile="true" transient="true" derived="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="get" value="return (this.getPushesTo() != null);"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="repository" nsURI="http://palladiosimulator.org/Indirections/Repository/1.0"
      nsPrefix="org.palladiosimulator.indirections.repository">
    <eClassifiers xsi:type="ecore:EClass" name="DataSinkRole" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/ProvidedRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataInterface" eType="#//repository/DataInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataSourceRole" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/RequiredRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataInterface" eType="#//repository/DataInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataInterface" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Interface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSignature" lowerBound="1"
          eType="#//repository/DataSignature" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataSignature" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Signature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataChannel" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/RepositoryComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>Note that this class is also a {@link ResourceInterfaceRequiringEntity}&lt;/p> &lt;p>TODO: validation for derived attribute should be implemented (type must be DataSinkRole/DataSourceRole)&lt;/p>"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSinkRoles" upperBound="-1"
          eType="#//repository/DataSinkRole" changeable="false" volatile="true" transient="true"
          derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="get" value="return (EList&lt;DataSinkRole>) ((EList&lt;?>) getProvidedRoles_InterfaceProvidingEntity());"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSourceRoles" upperBound="-1"
          eType="#//repository/DataSourceRole" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="get" value="return (EList&lt;DataSourceRole>) ((EList&lt;?>) getRequiredRoles_InterfaceRequiringEntity());"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaClassDataChannel" eSuperTypes="#//repository/DataChannel #//JavaClassRealization"/>
  </eSubpackages>
</ecore:EPackage>
