<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="indirection" nsURI="http://palladiosimulator.org/Indirection/1.0"
    nsPrefix="org.palladiosimulator.simulizar.indirection">
  <eSubpackages name="actions" nsURI="http://palladiosimulator.org/Indirection/Actions/1.0"
      nsPrefix="org.palladiosimulator.simulizar.indirection.actions">
    <eClassifiers xsi:type="ecore:EClass" name="AnalyseStackAction" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/AbstractAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumeEventAction" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/AbstractAction ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/CallAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/EventType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sinkRole" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/SinkRole"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="datatypes" nsURI="http://palladiosimulator.org/Indirection/Datatypes/1.0"
      nsPrefix="org.palladiosimulator.simulizar.indirection.datatypes">
    <eClassifiers xsi:type="ecore:EEnum" name="Scheduling">
      <eLiterals name="FirstInFirstOut"/>
      <eLiterals name="LastInFirstOut" value="1"/>
      <eLiterals name="Priority" value="2"/>
      <eLiterals name="Random" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PutPolicy">
      <eLiterals name="Blocking" literal=""/>
      <eLiterals name="DiscardFirstIn" value="1"/>
      <eLiterals name="DiscardLastIn" value="2"/>
      <eLiterals name="DiscardIncoming" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="WindowingTimeMode">
      <eLiterals name="WallClock" literal="WallClock"/>
      <eLiterals name="Timestamp" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Aggregation">
      <eLiterals name="Average"/>
      <eLiterals name="ExactlyOne" value="1"/>
      <eLiterals name="Count" value="2"/>
      <eLiterals name="First" value="3"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="partitioning" nsURI="http://palladiosimulator.org/Indirection/Partitioning/1.0"
      nsPrefix="org.palladiosimulator.simulizar.indirection.partitioning">
    <eClassifiers xsi:type="ecore:EClass" name="Partitioning"/>
    <eClassifiers xsi:type="ecore:EClass" name="Windowing">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeMode" lowerBound="1"
          eType="#//datatypes/WindowingTimeMode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="system" nsURI="http://palladiosimulator.org/Indirection/System/1.0"
      nsPrefix="org.palladiosimulator.simulizar.indirection.system">
    <eClassifiers xsi:type="ecore:EClass" name="DataChannel" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/EventChannel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" transient="true"
          defaultValueLiteral="-1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduling" lowerBound="1"
          eType="#//datatypes/Scheduling" defaultValueLiteral="FirstInFirstOut"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="putOverCapacityPolicy"
          lowerBound="1" eType="#//datatypes/PutPolicy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="partitioning" eType="#//partitioning/Partitioning"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="windowing" eType="#//partitioning/Windowing"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockIfNotAvailable"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumersAreCompeting"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEventGroup" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/EventGroup"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sinkEventGroup" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/EventGroup"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
